<?php
/*
* functions-genre.php
* This file should be included from functions.php

This WordPress plugin was developed for the Olathe Public Library, Olathe, KS
http://www.olathelibrary.org

Copyright (c) 2010, Chris Sammis
http://csammisrun.net/

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*
*/

function SRP_PrintGenreOptions()
{
    //csnote DO NOT START ANY ID AT ZERO.  PHP HAS MAJOR ISSUES WITH ZERO.  SERIOUSLY.
    $gid = is_srptheme_option_set('nextgenreid') ? get_srptheme_option('nextgenreid') : 1;
?>
<div>Configure the genres available for book reviews.  The list will be alphabetized when the users select genres for their reviews and reading entries.</div>
<div>&nbsp;</div>
<!-- Set up the form variables for nondecreasing genre IDs -->
<input type="hidden" id="nextgenreid" name="nextgenreid" value="<?php echo $gid; ?>" />
<!-- Javascript for genre table manipulation -->
<script language="javascript">
function addGenreRow(genreId, genreName)
{
    if (genreName === undefined)
    {
        genreName = "";
    }
    
    if (genreId === undefined)
    {
        // Get the next group index
        var nextGenreIdField = document.getElementById('nextgenreid');
        genreId = parseInt(nextGenreIdField.getAttribute('value'));
        nextGenreIdField.setAttribute('value', genreId + 1);
    }
    
    var parent = document.getElementById("srp_allgenres");
    
    var genregroup = document.createElement("div");
    genregroup.id = 'srp_genrerow' + genreId;
    genregroup.setAttribute('class', 'srp_genre');
    genregroup.setAttribute('style',
                             'border-left:solid 0.2em black; border-bottom:solid 0.1em black; padding-left:0.5em; margin-bottom:0.75em');

    var namegroup = document.createElement("div");
    var namelabel = document.createElement("span");
    namelabel.innerHTML = "Genre name:&nbsp;";
    var namename = document.createElement("input");
    namename.setAttribute('class', 'text');
    namename.setAttribute('type', 'text');
    namename.setAttribute('size', 40);
    namename.setAttribute('name', 'srp_genre' + genreId);
    namename.setAttribute('value', genreName);
    var nameremove = document.createElement('span');
    nameremove.setAttribute('style', 'margin-left:2em; font-size:smaller; vertical-align:middle');
    nameremove.innerHTML = "<a href=\"javascript:deleteGenreRow(" + genreId + ");\">Remove this genre</a>";
    namegroup.appendChild(namelabel);
    namegroup.appendChild(namename);
    namegroup.appendChild(nameremove);
    
    genregroup.appendChild(namegroup);
    
    parent.appendChild(genregroup);
}

function deleteGenreRow(genrenumber)
{
    var parent = document.getElementById("srp_allgenres");
    for (var i = 0; i < parent.childNodes.length; i++)
    {
        var div = parent.childNodes[i];
        if (div.id == ("srp_genrerow" + genrenumber))
        {
            parent.removeChild(div);
            break;
        }
    }
}
</script>
<!-- Javascript for loading data (calls are autogenerated) -->
<script language="javascript">
window.onload = function loadExistingGenres()
{
<?php
    $options = get_option('SRPTheme');
    ksort($options);
    
    $optionkeys = array_keys($options);
    for ($i = 0; $i < count($optionkeys); $i++)
    {
        $key = $optionkeys[$i];
        $pos = strpos($key, 'srp_genre');
        if ($pos === false || $pos != 0)
        {
            continue;
        }

        $genreid = substr($key, strlen('srp_genre'));
        $genrename = $options[$key];
        echo "addGenreRow($genreid, '$genrename');\n";
    }
?>
}
</script>

<div id="srp_allgenres"></div> <!-- container for DOM-manipulated genre entries -->
<div>&nbsp;</div>
<div><a href="javascript:addGenreRow();">Add genre</a></div>


<script language="javascript">
    function confirmSubmission()
    {
        return true;
    }
</script>
<?php
}
?>
